spring.application.name=ee_lektion_5
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/messageDb
spring.r2dbc.username=postgres
spring.r2dbc.password=Popkanin222
spring.flyway.url=jdbc:postgresql://localhost:5432/messageDb
spring.flyway.user=postgres
spring.flyway.password=Popkanin222


